version: 2.1

orbs:
  maven: circleci/maven@1.2.0
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16

release-args: &release-args
  mvn-release-perform-command: mvn --batch-mode release:perform -s .circleci/.maven.xml -PbuildKar
  ssh-fingerprints: "c2:55:b5:e6:c1:20:27:2b:79:2a:e7:3c:d6:78:11:2c"
  context: rso-base
  filters:
    branches:
      only: master

executors:
  openjdk8:
    docker:
      - image: 'cimg/openjdk:8.0'

jobs:
  build_and_test:
    executor: openjdk8
    steps:
      - checkout
      - maven/with_cache:
          verify_dependencies: false
          steps:
            - run:
                name: Run Maven Build
                command: |
                  mvn clean --batch-mode verify -PbuildKar -Dit
      - run:
          name: Save test results
          command: |
            mkdir -p ~/project/artifacts/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/project/artifacts/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/project/artifacts/junit/ \;
          when: always
      - store_test_results:
          path: ~/project/artifacts/junit
      - store_artifacts:
          path: ~/project/artifacts/it-reports

workflows:
  build-branch:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: master

  run-release:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - approve-release
          <<: *release-args

  release-from-master:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - build_and_test
          <<: *release-args
